In [1]:
print("hello world")

hello world


# array

In [2]:
import numpy as np
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


# Dimension

In [3]:
import numpy as np
array = np.array([1,2,3,4,5])
print(array,array.ndim)


[1 2 3 4 5] 1


In [11]:
import numpy as np
array = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(array,array.ndim,array.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 2 10


In [1]:

import numpy as np
array1 = np.array([1,2,3,4,5])
print(array1[1:3])


[2 3]


In [2]:

import numpy as np
array1 = np.array([10,20,30,40,50,60,70])
print(array1[1:3])


[20 30]


pandas

In [1]:
import pandas as pd
data={
    'Name':['Tom','Jerry','Mike','Harry'],
    'Age':[25,30,28,35],
    'City':['New York','Boston','Chicago','San Francisco']

}
df= pd.DataFrame(data)


In [2]:
df

Name  Age           City
0    Tom   25       New York
1  Jerry   30         Boston
2   Mike   28        Chicago
3  Harry   35  San Francisco

In [3]:
import pandas as pd
data={
    'Name':['Tom','Jerry','Mike','Harry'],
    'Age':[25,30,28,35],
    'City':['New York','Boston','Chicago','San Francisco']

}
df= pd.Series(data)


In [4]:
df

Name                     [Tom, Jerry, Mike, Harry]
Age                               [25, 30, 28, 35]
City    [New York, Boston, Chicago, San Francisco]
dtype: object

In [5]:
import pandas as pd

data = {
    'Name': ['John', 'Jane', 'Jack', 'Jill'],
    'Age': [20, 30, 25, 35],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.read_csv("df.csv")


In [6]:
df

Empty DataFrame
Columns: [marks, percentage]
Index: []

In [19]:
import numpy as np 
array = np.array([[[1,2],[3,5]],[[7,8],[10,11]]])
print(array,array.ndim)

[[[ 1  2]
  [ 3  5]]

 [[ 7  8]
  [10 11]]] 3
